#ifndef TEST_PROFILES_GLOBAL_MP_H
#define TEST_PROFILES_GLOBAL_MP_H

#include "ProjectConfig.h"

#if TEST_SUITE == TEST_SUITE_GLOBAL_MP

#if TEST_NR == 1
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     30
#elif TEST_NR == 2
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     30
#elif TEST_NR == 3
#define MAXIMUM_PERIODIC_TASKS    3
#define MAXIMUM_APERIODIC_TASKS   0
#define TEST_DURATION_TICKS       40
#define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 4
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     40
#elif TEST_NR == 5
#define MAXIMUM_PERIODIC_TASKS    3
#define MAXIMUM_APERIODIC_TASKS   0
#define TEST_DURATION_TICKS       140
#define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 6
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 7
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 8
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 9
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 10
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 11
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 12
#define MAXIMUM_PERIODIC_TASKS  101
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     1000
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 13
#define MAXIMUM_PERIODIC_TASKS  101
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     1000
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 14
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     50
// #define PERFORM_ADMISSION_CONTROL 0
#elif TEST_NR == 15
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     50
// #define PERFORM_ADMISSION_CONTROL 0

#else
#error "Invalid or undefined TEST_NR for GLOBAL_MP profile"
#endif // TEST_NR

#endif // TEST_SUITE == TEST_SUITE_GLOBAL_MP

#endif // TEST_PROFILES_GLOBAL_MP_H
