#ifndef TEST_PROFILES_PARTITIONED_MP_H
#define TEST_PROFILES_PARTITIONED_MP_H

#include "ProjectConfig.h"

#if TEST_SUITE == TEST_SUITE_PARTITIONED_MP

#if TEST_NR == 1
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     11
#elif TEST_NR == 2
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     23
#elif TEST_NR == 3
#define MAXIMUM_PERIODIC_TASKS  100
#define MAXIMUM_APERIODIC_TASKS 0
#define SHARED_STACK_SIZE       64
#elif TEST_NR == 4
#define MAXIMUM_PERIODIC_TASKS  100
#define MAXIMUM_APERIODIC_TASKS 0
#define SHARED_STACK_SIZE       64
#define TEST_DURATION_TICKS     0
#elif TEST_NR == 5
#define MAXIMUM_PERIODIC_TASKS  10
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 6
#define MAXIMUM_PERIODIC_TASKS  10
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 7
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     400
#elif TEST_NR == 8
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 9
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     1360
#elif TEST_NR == 10
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     1000
#elif TEST_NR == 11
#define MAXIMUM_PERIODIC_TASKS    2
#define MAXIMUM_APERIODIC_TASKS   0
#define PERFORM_ADMISSION_CONTROL 0
#define TEST_DURATION_TICKS       250
#elif TEST_NR == 12
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     27
#elif TEST_NR == 13
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     40
#elif TEST_NR == 14
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 15
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     37
#else
#error "Invalid or undefined TEST_NR for partitioned MP profile"
#endif // TEST_NR

#endif // TEST_SUITE == TEST_SUITE_PARTITIONED_MP

#endif // TEST_PROFILES_PARTITIONED_MP_H
