#ifndef TEST_PROFILES_CBS_H
#define TEST_PROFILES_CBS_H

#include "ProjectConfig.h"

#if TEST_SUITE == TEST_SUITE_CBS

#if TEST_NR == 1
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     21
#elif TEST_NR == 2
#define MAXIMUM_PERIODIC_TASKS  0
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     10
#elif TEST_NR == 3
#define MAXIMUM_PERIODIC_TASKS  0
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 4
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     30
#elif TEST_NR == 5
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 6
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 2
#define TEST_DURATION_TICKS     53
#elif TEST_NR == 7
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 2
#define TEST_DURATION_TICKS     70
#elif TEST_NR == 8
#define MAXIMUM_PERIODIC_TASKS  0
#define MAXIMUM_APERIODIC_TASKS 2
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 9
#define MAXIMUM_PERIODIC_TASKS  0
#define MAXIMUM_APERIODIC_TASKS 2
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 10
#define MAXIMUM_PERIODIC_TASKS  0
#define MAXIMUM_APERIODIC_TASKS 3
#define TEST_DURATION_TICKS     80
#elif TEST_NR == 11
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 2
#define TEST_DURATION_TICKS     100
#elif TEST_NR == 12
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 3
#define TEST_DURATION_TICKS     100
#elif TEST_NR == 13
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     21
#elif TEST_NR == 14
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     21
#elif TEST_NR == 15
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 16
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 17
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     50
#elif TEST_NR == 18
#define MAXIMUM_PERIODIC_TASKS  1
#define MAXIMUM_APERIODIC_TASKS 1
#define TEST_DURATION_TICKS     50
#else
#error "Invalid or undefined TEST_NR"
#endif // TEST_NR

#endif // TEST_SUITE == TEST_SUITE_CBS

#endif // TEST_PROFILES_CBS_H
