#ifndef TEST_PROFILES_EDF_H
#define TEST_PROFILES_EDF_H

#ifdef TEST_NR

#if TEST_NR == 1
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     11
#elif TEST_NR == 2
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     23
#elif TEST_NR == 3
#define MAXIMUM_PERIODIC_TASKS  100
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 4
#define MAXIMUM_PERIODIC_TASKS  100
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 5
#define MAXIMUM_PERIODIC_TASKS  10
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 6
#define MAXIMUM_PERIODIC_TASKS  10
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 7
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     400
#elif TEST_NR == 8
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#elif TEST_NR == 9
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     1200
#elif TEST_NR == 10
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     1000
#elif TEST_NR == 11
#define MAXIMUM_PERIODIC_TASKS    2
#define MAXIMUM_APERIODIC_TASKS   0
#define PERFORM_ADMISSION_CONTROL 0
#define TEST_DURATION_TICKS       250
#else
#error "Invalid or undefined TEST_NR for EDF profile"
#endif

#endif // TEST_NR

#endif // TEST_PROFILES_EDF_H
