#ifndef TEST_PROFILES_GLOBAL_MP_H
#define TEST_PROFILES_GLOBAL_MP_H

#include "ProjectConfig.h"

#if TEST_SUITE == TEST_SUITE_GLOBAL_MP

#endif // TEST_SUITE == TEST_SUITE_GLOBAL_MP

#endif // TEST_PROFILES_GLOBAL_MP_H
