#ifndef TEST_PROFILES_GLOBAL_MP_H
#define TEST_PROFILES_GLOBAL_MP_H

#include "ProjectConfig.h"

#if TEST_SUITE == TEST_SUITE_GLOBAL_MP

#if TEST_NR == 1
#define MAXIMUM_PERIODIC_TASKS  2
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     30
#elif TEST_NR == 2
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     40
#elif TEST_NR == 3
#define MAXIMUM_PERIODIC_TASKS  3
#define MAXIMUM_APERIODIC_TASKS 0
#define TEST_DURATION_TICKS     140
#else
#error "Invalid or undefined TEST_NR for GLOBAL_MP profile"
#endif // TEST_NR

#endif // TEST_SUITE == TEST_SUITE_GLOBAL_MP

#endif // TEST_PROFILES_GLOBAL_MP_H
